version: "3.8"
name: ponder-poll

services:
  postgres-db:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    extends:
      file: common.yaml
      service: app
    command: celery -A ponder_poll.celery worker -l info
    depends_on:
      - redis

  celery-beat:
    extends:
      file: common.yaml
      service: app
    command: celery -A ponder_poll.celery beat -l info
    depends_on:
      - redis
      - celery

  ponder-poll:
    extends:
      file: common.yaml
      service: app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres-db
      - celery
      - celery-beat

volumes:
  postgres-db:
