# Generated by Django 4.2.7 on 2023-12-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote',
        ),
        migrations.RemoveField(
            model_name='option',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.AlterField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('poll', 'text'), name='unique_option'),
        ),
    ]
